=== kelemen9/XBG3S6WebXML/XBG3S6_1015/XBG3S6_XMLSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified" attributeFormDefault="unqualified">

<!-- Egyszerű típusok – felépítése -->
<xs:element name="vendeglatas" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="etterem" type="EtteremTipus" maxOccurs="unbounded"/>
            <xs:element name="foszakacs" type="FoszakacsTipus" maxOccurs="unbounded"/>
            <xs:element name="szakacs" type="SzakacsTipus" maxOccurs="unbounded"/>
            <xs:element name="gyakornok" type="GyakornokTipus" maxOccurs="unbounded"/>
            <xs:element name="rendeles" type="RendelesTipus" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<!--Kulcsok-->

    <xs:key name="etterem_kulcs">
        <xs:selector xpath="etterem" />
        <xs:field xpath="ekod" />
    </xs:key>

     <xs:key name="gyakornok_kulcs">
        <xs:selector xpath="gyakornok" />
        <xs:field xpath="gykod" />
    </xs:key>

     <xs:key name="foszakacs_kulcs">
        <xs:selector xpath="foszakacs" />
        <xs:field xpath="fkod" />
    </xs:key>

     <xs:key name="gyakornok_kulcs">
        <xs:selector xpath="gyakornok" />
        <xs:field xpath="kod" />
    </xs:key>

     <xs:key name="vendeg_kulcs">
        <xs:selector xpath="vendeg" />
        <xs:field xpath="e_v" />
    </xs:key>

<!-- Idegen kulcs-->

       <xs:keyref refer="etterem_kulcs" name="etterem_idegen_kulcs">
        <xs:selector xpath="rendeles" />
        <xs:field xpath="e_v_v" />
       </xs:keyref>

        <xs:keyref refer="etterem_kulcs" name="etterem_idegen_kulcs">
        <xs:selector xpath="rendeles" />
        <xs:field xpath="e_v_v" />
       </xs:keyref>


        <xs:keyref refer="etterem_kulcs" name="etterem_gyakornok_kulcs">
        <xs:selector xpath="rendeles" />
        <xs:field xpath="e_v_v" />
        </xs:keyref>



<!-- Komplex tipusok-->

    <xs:complexType name="etteremTipus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="cim" type="xs:Tipus"/>
            <xs:element name="csillag" type="xs:Integer"/>
        </xs:sequence>
        <xs:attribute name="ekod" type="xs:string" use="required" />
    </xs:complexType>


    <xs:complexType name="foszakacsTipus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="eletkor" type="xs:string"/>
            <xs:element name="vegzettseg" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="fkod" type="xs:string" use="required" />
        <xs:attribute name="e_f" type="xs:string" use="required" />
    </xs:complexType>

      <xs:complexType name="szakacsTipus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="eletkor" type="xs:string"/>
            <xs:element name="vegzettseg" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="szkod" type="xs:string" use="required" />
        <xs:attribute name="e_sz" type="xs:string" use="required" />
    </xs:complexType>


  <xs:complexType name="gyakorlatTipus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="gyakorlat" type="xs:gyakorlatTipus"/>
            <xs:element name="muszak" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="gykod" type="xs:string" use="required" />
        <xs:attribute name="e_gy" type="xs:string" use="required" />
    </xs:complexType>

        <xs:complexType name="gyakorlatTipus">
            <xs:sequence>
                <xs:element name="kezdete" type="xs:string" />
                 <xs:element name="idotartam" type="xs:string" />
            </xs:sequence>
        </xs:complexType>


    <!-- Rendeles-->


  <xs:complexType name="rendekesTipus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="osszeg" type="xs:gyakorlatTipus"/>
            <xs:element name="etel" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="gykod" type="xs:string" use="required" />
        <xs:attribute name="e_gy" type="xs:string" use="required" />
    </xs:complexType>

        <xs:complexType name="gyakorlatTipus">
            <xs:sequence>
                <xs:element name="kezdete" type="xs:string" />
                 <xs:element name="idotartam" type="xs:string" />
            </xs:sequence>
        </xs:complexType>

=== kelemen9/XBG3S6WebXML/XBG3S6_1015/XBG3S6_XML.xml
<?xml version="1.0" encoding="utf-8"?>

<vendeglatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XBG3S6_XMLSchema.xsd">

<!-- Elemek -->
<etterem ekod="e1">
    <nev>..</nev>
    <cim>
        <varos>Budapest</varos>
        <utca>Visegrádi</utca>
        <hazszam>13</hazszam>
    </cim>
    <csillag>5</csillag>
</etterem>

<!-- Foszakacsok -->

<foszakacs fkod="f1" e_f="e1">
    <nev>Havas Péter</nev>
    <eletkor>35</eletkor>
    <vegzettseg>szakkozepiskola</vegzettseg>
    <vegzettseg>Intitut Paul Bocouese</vegzettseg> 
</foszakacs>

<foszakacs fkod="f2" e_f="e2">
    <nev>Nagy Károly</nev>
    <eletkor>30</eletkor>
    <vegzettseg>La Cordon Bleu</vegzettseg> 
</foszakacs>


<!-- Szakacsok -->

<szakacs szkod="sz1" e_sz="e1">
    <nev>Ötlet Elek</nev>
    <reszleg>Saucler</reszleg>
    <vegzettseg>Szakkozepiskola</vegzettseg>
    <vegzettseg>La Cordon Bleu</vegzettseg> 
    <vegzettseg>Intitut Paul Bocouese</vegzettseg> 
</szakacs>

<szakacs szkod="sz2" e_sz="e2">
    <nev>Kocsis Tibor</nev>
    <reszleg>Entremetier</reszleg>
    <vegzettseg>Szakkozepiskola</vegzettseg>
    <vegzettseg>La Cordon Bleu</vegzettseg> 
</szakacs>

<szakacs szkod="sz3" e_sz="e3">
    <nev>Tálas Levente</nev>
    <reszleg>Entremetier</reszleg>
    <vegzettseg>La Cordon Bleu</vegzettseg> 
     <vegzettseg>Intitut Paul Bocouese</vegzettseg> 
</szakacs>

<szakacs szkod="sz4" e_sz="e4">
    <nev>Valami Judit</nev>
    <reszleg>Entremetier</reszleg>
    <vegzettseg>La Cordon Bleu</vegzettseg> 
     <vegzettseg>Intitut Paul Bocouese</vegzettseg> 
</szakacs>

<!-- Gyakornok -->

<gyakornok gykod="1" e_gy="e1">
    <nev>Bordás Dávid</nev>
    <gyakorlat>
        <kezdete>2021.08.20</kezdete>
        <idotartam>2 honap</idotartam>
    </gyakorlat>
    <muszak>Délelőtt</muszak>
    <muszak>Este</muszak>
</gyakornok>

<gyakornok gykod="2" e_gy="e2">
    <nev>Szilágyi István</nev>
    <gyakorlat>
        <kezdete>2021.06.01</kezdete>
        <idotartam>4 honap</idotartam>
    </gyakorlat>
    <muszak>Délután</muszak>
</gyakornok>

<!-- Vendeg -->

<vendeg vkod="1" v="v1">
    <nev>Fekete Péter</nev>
    <eletkor>21</eletkor>
    <cim>
        <varos>Miskolc</varos>
        <utca>Márton</utca>
        <hazszam>17</hazszam>
    </cim>
</vendeg>

<vendeg vkod="2" v="v2">
    <nev>Bordás Áron</nev>
    <eletkor>25</eletkor>
    <cim>
        <varos>Miskolc</varos>
        <utca>Márton</utca>
        <hazszam>17</hazszam>
    </cim>
</vendeg>

<!-- Rendeles -->

<rendeles e_v_v="e1" e_v_v="v1">
    <osszeg>8000</osszeg>
    <etel>Kaviar</etel>
</rendeles>

<rendeles e_v_v="e2" e_v_v="v2">
    <osszeg>8000</osszeg>
    <etel>Steak</etel>
</rendeles>

<rendeles e_v_v="e3" e_v_v="v3">
    <osszeg>18000</osszeg>
    <etel>Zsiros kenyer</etel>
</rendeles>

<rendeles e_v_v="e4" e_v_v="v4">
    <osszeg>400</osszeg>
    <etel>Macko sajt</etel>
</rendeles>

</vendeglatas>
